# ==============================================================================
# Configure version info
#
# This file's sole purpose is to generate config.hpp from config.hpp.in
# ==============================================================================

configure_file(
  input: 'config.hpp.in',
  output: 'config.hpp',
  configuration: asmgrader_conf_data
)
