#!/bin/sh

# Exit upon error (of build and test scripts)
set -e

echo "[pre-push] Checking that project builds and that all tests pass"

REPO_ROOT=$(git rev-parse --show-toplevel)

>/dev/null 2>&1 "$REPO_ROOT/build.sh" || (echo "[pre-push] Build failed!" && exit 1)
>/dev/null 2>&1 "$REPO_ROOT/test.sh" || (echo "[pre-push] Test(s) failed!" && exit 1)
