#!/usr/bin/env bash

#
# Lint project with various static analysis tools
#

# Exit on error; exit status of pipeline is nonzero if any command fails
set -eo pipefail

jobs=12

usage() {
    cat <<EOF
Usage: lint [OPTIONS] [FILE]...
Lint entire project or only specified FILE(s) according to OPTIONS.

Arguments:
    [FILE]  files to lint; defaults to linting entire project if left unspecified

Options:
    -h, --help                print this help message
    -j JOBS, --jobs JOBS      Number of threads to use. Fallbacks are env{JOBS} then nproc(1)
    -n, --dry-run             print commands instead of executing them
    --use TOOLS               Comma seperated linting tool(s) to use. Defaults to CodeChecker if available,
                              otherwise 'clang-format,clang-tidy,cppcheck'
    --database DATABASE       compile_commands.json database to use, or containing directory
EOF
} >&2

readarray -t lint_files < <(
    find src/ include/ tests/ examples/ -name '*.hpp' -or -name '*.cpp'
)

compilation_db=./build/unixlike-clang-ninja-release/compile_commands.json #"$(find build/ -name compile_commands.json -not -path '*cross*' -not -path '*docs*' | sort | head -n1)"

# shellcheck disable=SC2034
readarray -t cmake_files < <(
    find . -name 'CMakeLists.txt' -or -name '*.cmake' -not -path 'build'
)

# Run a group of commands in parallel. Displays a progress bar.
# Args:
#   $1     maxjobs  : maximum number of jobs
#   $2-... commands : commands, which are ;-seperated strings as "exec;args..."
parallel() {
    [[ $# -lt 2 ]] && return 1

    local maxjobs=$1
    shift

    local cmds=("$@")
    local -i num_cmds=${#cmds[@]}

    local -i running=0
    local -i done=0
    local -i retcode=0

    for cmd in "${cmds[@]}"; do
        eval "$cmd" &
        printf '[%3d/%3d] Running: %s\n' $((++done)) $num_cmds "$cmd"
        if [[ $((++running)) -ge $maxjobs ]]; then
            wait -n || retcode+=1
            ((--running))
        fi
    done

    while [[ -n $(jobs -r) ]]; do
        wait -n || retcode+=1
    done

    return $retcode
}

run_tools() {
    local -i cf_failed
    local -i ct_failed
    local -i cppc_failed

    echo
    echo "=========================================================="
    echo "Clang Format:"
    echo "=========================================================="
    readarray -t cf_cmds < <(
        printf 'clang-format %q --dry-run -Werror\n' \
            "${lint_files[@]}"
    )
    parallel $jobs "${cf_cmds[@]}" || cf_failed+=$?

    echo
    echo "=========================================================="
    echo "Clang Tidy"
    echo "=========================================================="
    header_filter="$(pwd)/(src|include|tests|examples)/.*"

    readarray -t ct_cmds < <(
        printf "clang-tidy %q --use-color -p \"$compilation_db\" --warnings-as-errors='*' --header-filter \"$header_filter\"\n" \
            "${lint_files[@]}"
    )
    parallel $jobs "${ct_cmds[@]}" || ct_failed+=$?

    echo
    echo "=========================================================="
    echo "Cppcheck"
    echo "=========================================================="
    cppcheck_dir=.cache/cppcheck
    mkdir -p $cppcheck_dir
    cppcheck_report=reports/cppcheck.xml

    cppcheck --project="$compilation_db" \
        -ibuild -i"${CPM_SOURCE_CACHE--}" \
        --check-level=exhaustive --max-ctu-depth=10 --enable=all --inconclusive \
        --platform=native \
        --inline-suppr --suppress=missingIncludeSystem \
        -j $jobs \
        --check-library \
        --library=gnu --library=boost --library=posix \
        --checkers-report=reports/cppcheck-checkers.txt \
        --cppcheck-build-dir=$cppcheck_dir \
        --xml --output-file=$cppcheck_report

    cppc_failed="$(grep -c '<error' $cppcheck_report)"

    echo
    echo '=========================================================='
    echo 'Summary'
    echo '=========================================================='
    printf '%-15s | %8s | %8s\n' 'Check' 'Passed' 'Failed'
    printf '%015d-|%010d|-%08d\n' 0 0 0 | tr '0' '-'
    printf '%-15s | %8d | %8d\n' 'clang-format' $((${#lint_files[@]} - cf_failed)) $cf_failed
    printf '%-15s | %8d | %8d\n' 'clang-tidy' $((${#lint_files[@]} - ct_failed)) $ct_failed
    printf '%-15s | %8s | %8d\n' 'cppcheck' 'n/a' $cppc_failed

    return $((cf_failed + ct_failed + cppc_failed))
}

run_codechecker() {
    local output_dir=reports/codechecker
    local html_output_dir=reports/codechecker-html
    local skipfile_path=/tmp/codechecker-skipfile.list

    cat >$skipfile_path <<EOF
-*/build/*
EOF
    if [[ -v CPM_SOURCE_CACHE ]]; then
        cat >>$skipfile_path <<EOF
-$CPM_SOURCE_CACHE/*
EOF
    fi

    echo '=========================================================='
    echo 'CodeChecker'
    echo '=========================================================='
    CodeChecker analyze "$compilation_db" \
        --skip $skipfile_path \
        -j $jobs \
        \
        --output $output_dir # --ctu \

    CodeChecker parse --export html --output $html_output_dir $output_dir
}

if command -v CodeChecker &>/dev/null; then
    run_codechecker
else
    run_tools
fi
