#!/usr/bin/env bash

#
# Util script to simplify running tests
#

usage() {
    cat <<EOF
Usage: utest [OPTIONS] [preset-opts]...

Arguments:
    [preset-opts]  build-type, compiler, generator
                   default triple is: debug-gcc-ninja

Options:
    -h, --help                print this help message
    -j JOBS, --jobs JOBS      Number of threads to use. Fallbacks are env{JOBS} then nproc(1)
    -n, --dry-run             print commands instead of executing them
    --no-build                do not attempt to build
EOF
} >&2

expand() {
    eval "IFS='|'; echo \"\${$1[*]}\""
}

cmd="cmake"

build_type="debug"
compiler="gcc"
generator="ninja"
fresh=
no_build=
jobs=${JOBS-$(nproc)}

cmake_args=()

# Process all args
while (($#)); do
    opt=${1,,} # transform to all lowercase
    case "$opt" in
    -n | --dry-run)
        dry_run=yes
        ;;
    --no-build)
        no_build=yes
        ;;
    --fresh)
        fresh="--fresh"
        ;;
    -h | --help)
        usage
        exit
        ;;
    -j | --jobs)
        if ! [[ $2 =~ ^[0-9]+$ ]]; then
            >&2 echo 'Specified JOBS arg is invalid'
            exit 1
        fi
        jobs="$2"
        shift
        ;;
    *)
        if [[ $opt =~ $(expand valid_build_types) ]]; then
            build_type="$opt"
        elif [[ $opt =~ $(expand valid_compilers) ]]; then
            compiler="$opt"
        elif [[ $opt =~ $(expand valid_generators) ]]; then
            generator="$opt"
        else
            >&2 echo 'Invalid option!' "($opt)"
            usage
            exit 1
        fi
        ;;
    esac
    shift
done

if [[ $jobs -gt $(nproc) ]]; then
    >&2 echo "Warning: number of jobs ($jobs) exceeds nproc ($(nproc)). Reducing to nproc."
    jobs=$(nproc)
fi

preset="unixlike-${compiler}-${generator}-${build_type}"

if [[ -z $no_build ]]; then
    preset+="-test"
    cmake_args+=(--workflow "$preset")
    [[ -n $fresh ]] && cmake_args+=("$fresh")
else
    cmd=ctest
    cmake_args+=(--preset "$preset")
fi

if [[ -n $dry_run ]]; then
    cat <<EOF
CMAKE_BUILD_PARALLEL_LEVEL="$jobs" CTEST_PARALLEL_LEVEL="$jobs" $cmd ${cmake_args[@]}
EOF
    exit
fi

echo -e "\e[4mTesting $preset\e[0m"
echo

CMAKE_BUILD_PARALLEL_LEVEL="$jobs" CTEST_PARALLEL_LEVEL="$jobs" $cmd "${cmake_args[@]}"
