set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CROSS_COMPILE aarch64-linux-gnu)

set(CMAKE_C_COMPILER   ${CROSS_COMPILE}-gcc)
set(CMAKE_CXX_COMPILER ${CROSS_COMPILE}-g++)
set(CMAKE_FIND_ROOT_PATH /usr/${CROSS_COMPILE})
# TODO: Fedora only?
list(APPEND CMAKE_FIND_ROOT_PATH /usr/lib/gcc/${CROSS_COMPILE}-linux-gnu)

# Search target libs/includes only in the sysroot
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
