# !!DISCLAIMER!!
# This was adapted from the following source
#   cpp-best-practices/cmake_template
#   https://github.com/cpp-best-practices/cmake_template/tree/1015c6b88410df411c0cc0413e3e64c33d7a8331
#   Courtesy of Jason Turner

name: ci

on:
  pull_request:
  push:
    tags:
    branches: [main]
  workflow_dispatch:

jobs:
  docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Doxygen and Graphviz
        uses: aminya/setup-cpp@v1
        with:
          doxygen: 1.12.0
          graphviz: true
          cmake: true
          ninja: true

      - name: Build Docs
        run: |
            make docs

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./build/html/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  test:
    name: ${{ matrix.os }} ${{ matrix.compiler }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc-11]  # TODO: Add llvm-14; cpptrace does not work without libgcc's _Unwind though
        build_type: [release] # TODO: Add debug mode
        # generator: [Ninja] # TODO: Maybe add Unix Makefiles
        os: [ubuntu-22.04, ubuntu-22.04-arm]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Setup Cache
        uses: ./.github/actions/setup_cache
        with:
          compiler: ${{ matrix.compiler }}
          build_type: ${{ matrix.build_type }}
          # generator: ${{ matrix.generator }}

      # CMake isn't detecting Ninja installed by setup-cpp
      # - name: Install Ninja
      #   run: |
      #     sudo apt-get update && sudo apt-get install -y ninja-build cmake
      #
      # - name: Check Ninja Install
      #   run: |
      #     ninja --version

      - name: Install Dependencies
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          cmake: true
          make: true
          # ninja: true
          ccache: true

      - name: Configure
        run: |
          cmake -S . -B build -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DASMGRADER_ENABLE_SANITIZER_ADDRESS=OFF \
          -DASMGRADER_BUILD_TESTS=ON -DASMGRADER_ENABLE_CACHE=ON -DASMGRADER_ENABLE_PCH=ON \
          --log-level=TRACE

      - name: Build
        run: |
          cd build && make

      - name: Test
        run: |
            ctest --test-dir build
