# !!DISCLAIMER!!
# This was adapted from the following source
#   cpp-best-practices/cmake_template
#   https://github.com/cpp-best-practices/cmake_template/tree/1015c6b88410df411c0cc0413e3e64c33d7a8331
#   Courtesy of Jason Turner

name: ci

on:
  pull_request:
    paths-ignore: ['docs/**']
  push:
    tags:
    branches: [main]
    paths-ignore: ['docs/**']
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.os }} ${{ matrix.compiler }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc-11]  # TODO: Add llvm-14; cpptrace does not work without libgcc's _Unwind though
        build_type: [debug, release]
        generator: [Ninja]
        os: [ubuntu-22.04, ubuntu-22.04-arm]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Setup Cache
        uses: ./.github/actions/setup_cache
        with:
          compiler: ${{ matrix.compiler }}
          build_type: ${{ matrix.build_type }}
          os: ${{ matrix.os }}
          generator: ${{ matrix.generator }}

      - name: Install Dependencies
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          cmake: true
          meson: true
          ninja: true
          ccache: true

      - name: Set CPM cache location
        run: |
          echo "MESON_PACKAGE_CACHE_DIR=~/.cache/meson-pkgs" >> $GITHUB_ENV

      # We want ccache to be capable of caching with a PCH
      - name: Set ccache Config
        run: |
          ccache --set-config 'sloppiness=pch_defines,time_macros,include_file_mtime,include_file_ctime'

      - name: Configure
        run: |
          meson setup build/ -Db_coverage=true

      - name: Build
        run: |
          meson compile -C build/

      - name: Test
        run: |
          LOG_LEVEL=trace meson test -C build/

      - name: Generate Coverage Reports
        run: |
          meson compile -C build/ coverage

      - name: ccache Stats
        run: |
          ccache -s -v

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: ./build/meson-logs
